# Generated by Django 4.2.11 on 2024-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
